### ISSUE TITLE
The code does crash: calling a method on nil in trace.rb

### ISSUE THREAD

**Issue by fabianfrz** [blong14/hawkular-apm-opentracing-ruby#1]
Error:
```
hawkular-apm-opentracing-ruby/lib/hawkular/trace.rb:162:in `finished_recur': undefined method `span' for nil:NilClass (NoMethodError)
        from hawkular-apm-opentracing-ruby/lib/hawkular/trace.rb:130:in `is_finished'
        from hawkular-apm-opentracing-ruby/lib/hawkular/apm_span.rb:96:in `finish'
        from ./bin/test.rb:13:in `<main>'
```

Sample code:
``` ruby
#!/usr/bin/env ruby

require "bundler/setup"
require "hawkular"
require 'pp'

OpenTracing.global_tracer = Hawkular::APMTracer.new()

span = OpenTracing.start_span("operation_name")
  med = OpenTracing.start_span("med", child_of: span)
    child = OpenTracing.start_span("child", child_of: med)
    child.finish
  med.finish
span.finish

pp span
```

This patch makes the library at least not crashing anymore (but does not fix the issue:
``` patch
diff --git a/lib/hawkular/trace.rb b/lib/hawkular/trace.rb
index 2e5efef..c8c6a09 100644
--- a/lib/hawkular/trace.rb
+++ b/lib/hawkular/trace.rb
@@ -1,5 +1,4 @@
 require 'hawkular/basic_utils'
-
 module Hawkular
 
   class Node
@@ -127,7 +126,7 @@ module Hawkular
 
       root_node = find_node(root_span.id)
 
-      finished_recur(root_node) ? root_node.span : nil
+      finished_recur(root_node) ? root_node&.span : nil
     end
 
     def find_node(span_id)
@@ -159,10 +158,10 @@ module Hawkular
     private
 
     def finished_recur(node)
+      return true unless node
       return nil if !node.span.is_finished?
 
-      nodes = node.nodes
-      nodes.each do
+      node.nodes.each do
         return nil if node.span.is_finished?
         return nil unless finished_recur(node)
       end
```

**Comment by blong14** [comment]
Hello!

Thanks for the issue and what looks to be a fix. I ran out of steam with this project due to this blog post: http://www.hawkular.org/blog/2017/04/19/hawkular-apm-jaeger.html

Should this library continue to exist? What is your primary use case? I am willing to continue plugging away (with hopefully your support) if there seems to be a need for this library. I will update the README to better reflect the current status of this project. Would you be willing to put in a pull request with this fix and test to support your fix?

Thanks again for reaching out.

Ben

**Comment by blong14** [comment]
@fabianfrz README has been updated to give a little context of where this library comes from and usage examples.

**Comment by fabianfrz** [comment]
Hi Ben,

* Should this library continue to exist?
  Probably yes but it should be moved to @opentracing-contrib. Performance monitoring is important and the library is currently the only one that exist.
* What is your primary use case?
  It would be cool if it would be possible to hook it into Rack (for support of Rails and Sinatra) as well as some custom servers.
* Would you be willing to put in a pull request with this fix and test to support your fix?
  **NO** The reason is that this is not a intended to be a fix for the issue. The trace is empty but at least there is no crash. The diff is just there to make it more easy to fix for you.

**Comment by blong14** [comment]
Hi @fabianfrz,

I spent some time looking at the landscape of an opentracing compliant ruby library and looks like a good place to start is here https://github.com/salemove/jaeger-client-ruby . 

Also, looks like the Jaeger server can be ran within docker:

docker run -d -p5775:5775/udp -p16686:16686 jaegertracing/all-in-one:latest

I think these two components together will handle your primary use case. 

I'm not sure that this library has much value anymore as the Hawkular team looks to not be focused on their backend (per the blog post I commented on earlier). 

Thanks

Ben
